sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:


  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1

  wechat:
    appid: wxdfacebedc4c6e293
    secret: 521042ae5977dfe2e1bbdc7a0b687a01
